#!/bin/bash

export curr_branch=$(git branch | grep "*" | sed "s/* //")
if [ "$curr_branch" = 'mastera' ]; then
   echo "Impossível Commitar no Branch MASTER: Commits devem ser feitos em branchs das respectivas issues"
   exit 1
fi
